### ISSUE TITLE
Unsupported fields in the descriptor

### ISSUE THREAD

**Issue by jjatria** [rolandomunoz/plugin_segment_finder#1]
The format of the descriptor (and the fields that need to be supported, etc) are still in discussion, so comments are more than welcome. The descriptor currently used by this plugin uses some fields that are not standard, let's say, so they will be ignored by the existing client.

In particular, I'm thinking of `Last_changes`, `Supported_by`, and `Project_director`.

If you want to have a change log, you could take a look at [the source code of the existing plugins](https://gitlab.com/cpran/). There, changes are kept in a separate `CHANGELOG` file, but this is currently not a standard thing (meaning you can choose how to do it). Regardless, they should not go in the descriptor.

The "supported by" should, I guess, go instead in the long description. I'd put the "project director" there as well, or maybe as another maintainer, depending on what his role is in the plugin (although in that case some people might contact him instead of you).

The short description field is really for short descriptions, more or less one line in length, a single sentence. For longer descriptions, you should use the long description field.

I'll send in a PR with an example.

**Comment by rolandomunoz** [comment]
Is is a good practice to end my files using extensions? For example, CHANGELOG.md and not CHANGELOG?

**Comment by jjatria** [comment]
Well, not _all_ files need extensions, but if you want to specify the format of the file. 

The corollary is that, if you want to make sure the format is _explicitly unspecified_ (because it might change in the future, or whatever), then it's probably a better idea to leave it out.

For example, a file `CHANGELOG.md` should definitely be in Markdown (otherwise it would be just plain confusing). But if you suddenly decide to start keeping your changes in YAML, then what do you do? Do you change the file name (breaking the URIs)? Or do you keep the extension (breaking expectations as to the format)?

Most Perl modules (to cite some previous art) use the filename `Changes` for their change logs. No extension. But some specify an extension (as in `Changes.pod` from `Locale::Codes`). For some more relevant previous art, all the plugins in CPrAN use `CHANGELOG`, but that's because of expected default values in GitLab...

It's up to you, really. Change logs are mostly for humans.
