### ISSUE TITLE
Version number should not go in repository name

### ISSUE THREAD

**Issue by jjatria** [rolandomunoz/plugin_segment_finder#3]
The current name of the plugin is "spanish_voiced_stops", but the repository is called "plugin_spanish_voiced_stops_v2.0.0". While the initial "plugin_" is desirable, the version number should not go in the repository name. If for nothing else, because when the next version is released, the name will be outdated.

Please rename the repository to "plugin_spanish_voiced_stops" (or more generally `"plugin_" + $plugin_name`), so that it can be cloned directly into the Praat preferences directory.

To mark the release number, please use instead a `tag`. In this case, like the one that you can create with `git tag v2.0.0`. For more information, please see [this document on tagging](https://git-scm.com/book/en/v2/Git-Basics-Tagging), or [the Github documentation on releases](https://help.github.com/articles/about-releases/).

**Comment by rolandomunoz** [comment]
It's done :)
